### ISSUE TITLE
Thread 1: EXC_BAD_ACCESS (code=1, address=0x0) on iOS 16.1

### ISSUE THREAD

**Issue by thanhnguyen198** [vmanot/Swallow#3]
@vmanot Hi , when i try run on iOS 16.6.1 then have error below. Could you help me check it ?
![Screenshot 2024-06-04 at 15 24 08](https://github.com/vmanot/Swallow/assets/102564688/54068919-102b-4ad8-9915-ffb48346eaa3)

**Comment by thanhnguyen198** [comment]
Lastest Version
![Screenshot 2024-06-04 at 15 32 38](https://github.com/vmanot/Swallow/assets/102564688/95c99972-d988-4135-a57a-9d5445d8d7d9)

**Comment by vmanot** [comment]
@thanhnguyen198 which version of Xcode are you on? And can you make a small sample Xcode project to reproduce this? I'll have it fixed ASAP.

**Comment by thanhnguyen198** [comment]
@vmanot  Xcode 14.1 and today i was updated Xcode to 15.2, but still can't run project and return this issue 
![Screenshot 2024-06-05 at 08 35 51](https://github.com/vmanot/Swallow/assets/102564688/a7425f23-c58d-47c2-ae21-ca1bc475caf8)

**Comment by vmanot** [comment]
@thanhnguyen198 unfortunately Xcode 15.4 will now be the minimum required version of Xcode for this package, given the compiler bugs in older versions.
