### ISSUE TITLE
Latest change broke Merge package

### ISSUE THREAD

**Issue by davidmoore1** [vmanot/Swallow#4]
You may already be adjusting this.  But the latest change here, removing _SwallowMacrosRuntime broke my import of AI, which uses your Merge which has this package as a dependency.  The Merge/module.swift imports _SwallowMacrosRuntime.  Not sure if I should have opened this against Swallow or Merge, but since they have the same owner, I figured it would get handled.  Thanks.

**Comment by vmanot** [comment]
@davidmoore1 sorry for the delayed reply, `SwallowMacrosRuntime` should be gone from both `Swallow` and `Merge`. Could you bump `Merge` up to the latest commit?
